title: Srujankumar Polepally # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a data scientist seeker with a passion for storytelling. I believe that words and data are the two most powerful tools to change the world.
  Most of my time is spent staring at a computer screen. During the day, I am usually programming, working to derive insight from large datasets. 
  I have developed a strong acumen for problem solving, and I enjoy an occasional challenge.
  <br><br>
  My skills include data analysis, visualization, and machine learning, Deep learning, Artificial learning
  <br><br>
  
  <a href="http://www.linkedin.com/in/srujankumar-polepally">View My LinkedIn Profile</a> 
  
  
  
  
theme: jekyll-theme-minimal
